import SideBar from '@/components/SideBar'
import { SessionProvider } from '@/components/SessionProvider'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'

import '../../styles/globals.css'
import Login from '@/components/Login'


export const metadata = {
  title: 'ChatGPT - Messenger',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          {!session ? (
            <Login />
          ): (

          <div className='flex'>
            <div className='bg-sidebarbg max-w-xs h-screen overflow-auto md:min-w-[20rem]'>
              <SideBar />
            </div>
            {/* ClienteProvider - Notification */}

            <div className="bg-primarybg flex-1">{children}</div>
          </div>
          )}
        </SessionProvider>
      </body>
    </html>
  )
}
